task_api_url=http://task.app.com/task1/api/v1
action_allow=A1|pending,1,20,plz check the status of order;A2|process,2,80,process the order now;A15|drop,200,9,abandon by user
allow_account=ABC,Admin,LTA,SPC,normal_auto_process

**

# 2026/09/02 xiao ming add for new service migration
serviceA_port=8888a
serviceA_url=http://serviceA-a.f99.tcomp.co
m
serviceA_pname=task/api/v2/delete      

account_task_mapping=ABC,new;LTA,process;User,drop
functions=action_allow,allow_account,task_api_url

old_serviceB_port=8888
old_serviceB_url=http://serviceB-a.f99.tcomp.com
old_serviceB_pname=task/api/v2/delete